version: 2

sources:
  - name: medicore # this is the source_name
    database: dbt

    tables:
      - name: aaa_aanvullend_medewerker
      - name: accountingexport
      - name: accountingexport_factuur
      - name: actinidium_user
      - name: activityimportrun
      - name: activitysetting
      - name: activitysetting_socialsupportactivity
      - name: activitysetting_systeemggzactiviteit
      - name: activitysetting_systeemggzbasisbehandelcomponent
      - name: activitysetting_zpmconsultation
      - name: address
      - name: admissionperiod
      - name: admissionperiodactivityzpm
      - name: appointment
      - name: appointment_extrastatus
      - name: appointment_sessionprofile
      - name: appointmentextrastatus
      - name: appointmentparticipation
      - name: appointmentstatus
      - name: appointmenttype
      - name: assurantienl
      - name: basicmhcactivity
      - name: batchstandard
      - name: behandeling
      - name: behandeling_careprofile
      - name: behandeling_socialsupportactivity
      - name: behandeling_systemwlzactivity
      - name: behandeling_systemwlzactivityminute
      - name: behandeling_verrichting_epdform_epdformdef
      - name: behandeling_verrichtinggroep
      - name: behandeling_wmoactivity_minute
      - name: behandeling_youthsupportactivity_minute
      - name: behandeling_zpmclosurelog
      - name: behandeling_zpmopeninglog
      - name: behandelingggz
      - name: behandelingggz_basis
      - name: behandelingggz_dbc
      - name: behandelingggz_ggzdiagnose
      - name: behandelingggz_systeemggzactiviteit
      - name: behandelingggz_systeemggzactiviteit_bu_dk
      - name: behandelingggz_systeemggzactiviteittijd
      - name: behandelingggz_systemmhcdiagnosisdsm5
      - name: behandelingjeugdhulp
      - name: behandelingprofiel
      - name: behandelingprofielggz_systeemggzactiviteit
      - name: behandelingredensluiten
      - name: behandelingverslag
      - name: behandelingzpmclosurelogactivity
      - name: bestanden
      - name: betaling
      - name: brief
      - name: careprofile
      - name: communicationmessage
      - name: communicationmessage_patient
      - name: communicationmessage_patientproductinstance
      - name: communicationstandard
      - name: contactmanner
      - name: contract
      - name: contractmunicipality
      - name: ctgactivity
      - name: debtor
      - name: declarationbatch
      - name: declarationbatch_factuur
      - name: declarationbatch_messages
      - name: disposition
      - name: dispositionallocatedproduct
      - name: dispositionallocatedproduct_behandeling
      - name: dispositionallocatedproductyouth
      - name: documentmanagementcategory
      - name: documentmanagementfile
      - name: documentmanagementfilebatch
      - name: documentmanagementfilecorrespondence
      - name: documentmanagementfileemruserform
      - name: documentmanagementfilepatient
      - name: documentmanagementfilezorgdomein
      - name: employee
      - name: employee_clinic
      - name: employee_menuitemgroup
      - name: employee_profession
      - name: employee_right
      - name: employee_systemprofession
      - name: employeelevel
      - name: employeetype
      - name: emrcategory
      - name: emrformvalues
      - name: emrnode
      - name: emrtemplateform
      - name: emrtype
      - name: emruserform
      - name: episode
      - name: episode_employee
      - name: episode_employeecasemanager
      - name: episode_employeecopractitioner
      - name: episode_employeepractitionerincharge
      - name: episode_referrer
      - name: episode_systemcarelabel
      - name: episode_systemdiagnosisbasicmhcprofile
      - name: episode_systemdiagnosisdsm5
      - name: episode_systemsetting
      - name: episodecarerequesttype
      - name: episodemhc
      - name: episodereferral
      - name: episodereferralreferrer
      - name: episodereferralreferrerexternal
      - name: episodereferralreferrerinternal
      - name: episodereferralreferrersystemexternal
      - name: episodezpmconsultation
      - name: episodezpmconsultation_bu_20220328
      - name: episodezpmconsultationgroup
      - name: episodezpmconsultationindividual
      - name: episodezpmconsultationindividualsurcharge
      - name: episodezpmconsultationindividualsurchargertms
      - name: episodezpmconsultationindividualsurchargetranslator
      - name: episodezpmconsultationindividualsurchargetraveltime
      - name: episodezpmconsultationregistration
      - name: episodezpmconsultationregistrationpatienttime
      - name: episodezpmconsultationregistrationpractitionertime
      - name: externalregistrationworkliststatus
      - name: factuur
      - name: factuur_tijd
      - name: factuuropdracht
      - name: factuuropdrachtregel
      - name: factuurregel
      - name: fin_contract
      - name: fin_contract_socialsupport
      - name: hf_import_act_act
      - name: hf_import_act_run
      - name: hf_import_act_validatie_result
      - name: invoice
      - name: invoiceablezpmperformance
      - name: invoiceablezpmperformanceconsultation
      - name: invoiceablezpmperformanceconsultationsurcharge
      - name: invoiceablezpmperformanceerror
      - name: invoiceablezpmperformancegroupconsultation
      - name: invoiceclinic
      - name: invoicedebtor
      - name: invoiceemployee
      - name: invoiceinsurance
      - name: invoiceline
      - name: invoicelineeffortorientedwmoproduct
      - name: invoicelineeffortorientedyouthsupportproduct
      - name: invoicelinegenericsocialsupportproduct
      - name: invoicelinegenericsocialsupportproductwmo
      - name: invoicelinegenericsocialsupportproductyouth
      - name: invoicelineoutputorientedwmoproduct
      - name: invoicelineoutputorientedyouthsupportproduct
      - name: invoicelinesocialsupportproducteffort
      - name: invoicelinesocialsupportproducteffort_treatmentactivity
      - name: invoicelinesocialsupportproductoutput
      - name: invoicelinezpm
      - name: invoicelinezpm_invoicelinezpmepisodebasicmhcprofile
      - name: invoicelinezpm_invoicelinezpmepisodecarelabel
      - name: invoicelinezpm_invoicelinezpmepisodedsm5
      - name: invoicelinezpmconsultationindividualsurcharge
      - name: invoicelinezpmconsultationregistration
      - name: invoicelinezpmconsultationregistration_bak
      - name: invoicelinezpmdayofstay
      - name: invoicelinezpmemployeepractitionerincharge
      - name: invoicelinezpmepisode
      - name: invoicelinezpmepisodecarelabel
      - name: invoicelinezpmepisodecarerequesttype
      - name: invoicelinezpmepisodediagnosisbasicmhcprofile
      - name: invoicelinezpmepisodediagnosisdsm5
      - name: invoicelinezpmepisodereferral
      - name: invoicelinezpmother
      - name: invoicepatient
      - name: invoicesocialsupport
      - name: invoicetreatment
      - name: invoicezpm
      - name: klantsettings
      - name: kliniek
      - name: koepelorganisatie
      - name: koepelorganisatie_maatschappij
      - name: koppeltaalpatient
      - name: log
      - name: log_objectid
      - name: maatschappij
      - name: maatschappijpakket
      - name: menuitem
      - name: menuitemgroep_menuitem
      - name: menuitemgroup
      - name: participant
      - name: participantgroup
      - name: participantgroupparticipation
      - name: patient
      - name: patient_clinic
      - name: patient_email
      - name: patient_patient
      - name: patientexternalreferrer
      - name: patientgroup
      - name: patientproduct
      - name: patientproduct_behandeling
      - name: patientproductinstance
      - name: patientproductinstanceallocated
      - name: patientproductwmo
      - name: patientproductyouthsupport
      - name: patientreferrerreason
      - name: periode
      - name: referrer
      - name: referrer_external
      - name: referrer_externalgp
      - name: referrer_internal
      - name: referrer_noreferrer
      - name: referrerindividual
      - name: referrerorganization
      - name: referrerorganizationtype
      - name: referrerselfinitiative
      - name: relatedorganization
      - name: resource
      - name: resourcetype
      - name: responsiblemunicipality
      - name: returnbatchvektis
      - name: returnbatchvektismessage
      - name: rosterrgrpparticipation_clinic
      - name: rosterrule
      - name: rosterrule_appointmenttype
      - name: rosterrulecache
      - name: rosterruleexception
      - name: rosterrulegroup
      - name: rosterrulegroup_clinic
      - name: rosterrulegroupparticipation
      - name: rosterruleprofile
      - name: scheduledprocess
      - name: scheduledprocessjob
      - name: socialsupportactivity
      - name: socialsupportinvoiceableproduct
      - name: socialsupportproduct
      - name: socialsupportproductwmo
      - name: socialsupportproductyouth
      - name: syslog
      - name: systeemdbcafsluitreden
      - name: systeemdeclarationretourbericht
      - name: systeemggzactiviteit
      - name: systeemggzbasisafsluitreden
      - name: systeemggzbasisbehandelcomponent
      - name: systeemggzbasisprestatiecode
      - name: systeemggzberoep
      - name: systeemggzcircuitcode
      - name: systeemggzdbctarief
      - name: systeemggzdiagnose
      - name: systeemggzprestatiecode
      - name: systeemggzproductgroep
      - name: systeemggzredensluiten
      - name: systeemggzverwijscode
      - name: systeemggzverwijscodejeugd
      - name: systeemggzzorgtype
      - name: systeemleefsituatie
      - name: systeemlogtype
      - name: systeemmaatschappijnl
      - name: systeemmenuitem
      - name: systeemopleidingsniveau
      - name: systeempostcodegebied
      - name: systeemspecialismenl
      - name: systeemzorgdomein
      - name: systeemzorginstelling
      - name: systeemzorgverlener
      - name: systeemzorgverlener_zorginstelling
      - name: systeemzorgverlenersoort
      - name: systemappointmentstatus
      - name: systemcakperiod
      - name: systemcarelabel
      - name: systemcarerequesttype
      - name: systemclosurereasonwmo
      - name: systemclosurereasonyouthsupport
      - name: systemconsultationsurcharge
      - name: systemcountry
      - name: systemdiagnosisbasicmhcprofile
      - name: systemdiagnosisdsm5
      - name: systemdiagnosismaingroup
      - name: systemdispositionregion
      - name: systemdsm5diagnosismaingroup
      - name: systemmhcdiagnosisdsm5
      - name: systemmunicipality
      - name: systemmunicipality_systemdispositionregion
      - name: systemparticipationrole
      - name: systemperformance
      - name: systempostalcode
      - name: systempostalcode_systemmunicipality
      - name: systemprofession
      - name: systemprofessionwithoutagb
      - name: systemreferraltype
      - name: systemregion
      - name: systemsetting
      - name: systemsocialsupportfrequency
      - name: systemsocialsupportunit
      - name: systemwlzactivity
      - name: systemwmoproductcategory
      - name: systemyouthregion
      - name: systemyouthsupportproductcategory
      - name: treatmentrelation
      - name: treatmentrelation_zorgtraject
      - name: vektis_batch
      - name: vektis_batchprocess
      - name: vektis_batchprocessjob
      - name: vektis_returnbatch
      - name: vektis_returnbatch_message
      - name: verrichting
      - name: verrichtingartikelgroep
      - name: verrichtinggroep
      - name: verrichtingkostprijs
      - name: verrichtingprijs
      - name: verrichtingprijsafspraak
      - name: werksituatie
      - name: woonvorm
      - name: zorgtraject
